### ISSUE TITLE
How to build my own .vsix to test out my new snippets

### ISSUE THREAD

**Issue by brandonmcclure** [Alpha1337k/makefile-boilerplate#1]
Thank you for the project! I wanted to use this to add some of my own snippets. VSCode has native functionality to run these extension projects in a debug instance which provides a nice quick check (just press F5!) that the snippet syntax is correct. I wanted to build/install my own separate extension while I was working on my snippets so that I could use the snippets as part of my regular workflow and quickly make small iterative changes as I go. 

I wrote a Makefile and some pwsh core build scripts in [PR 2](https://github.com/Alpha1337k/makefile-boilerplate/pull/2) that helped me accomplish that.

**Comment by Alpha1337k** [comment]
Hi Brandon, first of all, thank you for your interest in this project.

The problem / question i have is the following:

You wrote the script in powershell, which i'm fine with ( i would even go as far as liking the build.ps), but i don't understand why the `make package ` code was so complicated. I mean, ` vsce package` would do the trick right? It would also have the benefit of being more cross platform, and less dependent.

Hope to hear from you soon,
Thanks

**Comment by brandonmcclure** [comment]
You are right, the package task is just running microsoft's [vsce](https://github.com/Microsoft/vscode-vsce) program. I do not have nodejs installed so the docker approach lets me avoid adding a node js dependency. 

I am not sure what the most idomatic make syntax would be, but we could add a toggle like this to choose between the docker image and the local vsce
```
DockerBuild := true

ifeq ($(DockerBuild), true)
PackagePrefix := docker run --rm -v $${PWD}:/work bmcclure89/
endif

package:
	@$(PackagePrefix)vsce package -o bin/$(ExtensionName)-$(version).vsix
```

**Comment by Alpha1337k** [comment]
Something like that looks great! If you send a new pull request (or something else, not really familiar with pulling), ill add it to the main branch.

Thanks

**Comment by brandonmcclure** [comment]
I just updated the same pull request. I personally like to squash merge prs into main but commits are commits.
